version = 0.1
[default.pipeline_bootstrap.parameters]
pipeline_user = "arn:aws:iam::685075062616:user/aws-sam-cli-managed-dev-pipeline-resou-PipelineUser-IMtAjMa2JRIQ"
permissions_provider = "AWS IAM"

[dev.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::685075062616:role/aws-sam-cli-managed-dev-pipel-PipelineExecutionRole-axcC7943kNmr"
cloudformation_execution_role = "arn:aws:iam::685075062616:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionRo-sT9umRzgLhiX"
artifacts_bucket = "aws-sam-cli-managed-dev-pipeline-artifactsbucket-fw30249gcqx9"
image_repository = ""
region = "us-east-1"

[prod.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::685075062616:role/aws-sam-cli-managed-prod-pipe-PipelineExecutionRole-YQ2Ctc4gQ5gK"
cloudformation_execution_role = "arn:aws:iam::685075062616:role/aws-sam-cli-managed-prod--CloudFormationExecutionRo-17fCAXj4NGcU"
artifacts_bucket = "aws-sam-cli-managed-prod-pipeline-artifactsbucket-dx0ua1dtajeq"
image_repository = ""
region = "us-east-2"
