version = 0.1
[default.pipeline_bootstrap.parameters]
pipeline_user = "arn:aws:iam::685075062616:user/aws-sam-cli-managed-serverless-dev-pip-PipelineUser-mHUIxrCzNRjp"
permissions_provider = "AWS IAM"

[serverless-dev.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::685075062616:role/aws-sam-cli-managed-serverles-PipelineExecutionRole-TgPInGFUqoMa"
cloudformation_execution_role = "arn:aws:iam::685075062616:role/aws-sam-cli-managed-serve-CloudFormationExecutionRo-pGQPXGeSWDzV"
artifacts_bucket = "aws-sam-cli-managed-serverless-de-artifactsbucket-1vzuh99h5i9s5"
image_repository = ""
region = "us-east-1"

[serverless-prod.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::685075062616:role/aws-sam-cli-managed-serverles-PipelineExecutionRole-in23pZRIFxjS"
cloudformation_execution_role = "arn:aws:iam::685075062616:role/aws-sam-cli-managed-serve-CloudFormationExecutionRo-oSrQfkg5cAsR"
artifacts_bucket = "aws-sam-cli-managed-serverless-pr-artifactsbucket-1cz7opvspl9zv"
image_repository = ""
region = "us-east-2"
